import { useEffect, useState } from 'react';
import { Check, ChevronRight, FileText, Plus, RefreshCw, Search, X } from 'lucide-react';
import { call, desktop } from './api';
import type { Preferences, Theme } from './preferences';
import { SettingRow, SettingsGroup, SettingsSwitch } from './SettingsPage';
import { loadLocalSkills, skillSource, type Skill } from './skills';
import ExtensionsSettings from './ExtensionsSettings';
import AutomationSettings from './AutomationSettings';
import NotificationSettings from './NotificationSettings';
export type { Skill } from './skills';
export type ClientTab = 'appearance' | 'notifications' | 'personalization' | 'skills' | 'plugins' | 'automation';
const themeNames: Record<Theme, string> = { light: '白色', dark: '暗黑', graphite: '石墨', sand: '暖色', system: '跟随系统' };
export default function ClientSettings({ tab, prefs, setPrefs, projectId, busy, addSkill }: { tab: ClientTab; prefs: Preferences; setPrefs: (p: Preferences) => void; projectId: string; busy: boolean; addSkill: (s: Skill) => void }) {
  const [instructions, setInstructions] = useState(''); const [message, setMessage] = useState(''); const [error, setError] = useState(''); const [working, setWorking] = useState(false);
  const [search, setSearch] = useState(''); const [skills, setSkills] = useState<Skill[]>([]); const [warnings, setWarnings] = useState<string[]>([]); const [selected, setSelected] = useState<Skill>(); const [skillText, setSkillText] = useState(''); const [creating, setCreating] = useState(false); const [name, setName] = useState(''); const [description, setDescription] = useState('');
  const update = (key: keyof Preferences, value: unknown) => setPrefs({ ...prefs, [key]: value });
  async function run(action: () => Promise<void>) { setWorking(true); setError(''); setMessage(''); try { await action(); } catch (e) { setError(String(e)); } finally { setWorking(false); } }
  async function loadSkills() { const catalog = await loadLocalSkills(projectId, true); setSkills(catalog.skills); setWarnings(catalog.warnings ?? []); }
  useEffect(() => { if (!desktop) return; void run(async () => { if (tab === 'personalization') setInstructions((await call<{ instructions: string }>('get_client_preferences')).instructions); if (tab === 'skills') await loadSkills(); }); }, [tab, projectId]);
  if (tab === 'automation') return <AutomationSettings busy={busy}/>;
  if (tab === 'plugins') return <ExtensionsSettings projectId={projectId} busy={busy}/>;
  if (tab === 'notifications') return <NotificationSettings prefs={prefs} setPrefs={setPrefs}/>;
  return <div className={`client-settings-page${tab === 'skills' && !creating && !selected ? ' skills-catalog' : ''}`}><div className="settings-page-heading"><h2>{tab === 'appearance' ? '外观' : tab === 'personalization' ? '个性化' : tab === 'skills' ? '技能' : '自动化工具'}</h2><div>{tab === 'skills' ? <><span className="skill-list-count">{skills.length} 个</span><button className="icon-button" title="刷新技能" disabled={working || !desktop} onClick={() => void run(loadSkills)}><RefreshCw size={14} /></button><button className="quiet-button" disabled={!desktop || working || busy} onClick={() => { setCreating(true); setSelected(undefined); setSkillText(''); }}><Plus size={14} />新建</button></> : null}</div></div>{error ? <p className="cc-error" role="alert">{error}</p> : null}{message ? <p className="provider-feedback" role="status"><Check size={14} />{message}</p> : null}
    {tab === 'appearance' ? <>
      <SettingsGroup title="主题"><div className="theme-grid">{Object.entries(themeNames).map(([id, label]) => <button key={id} aria-pressed={prefs.theme === id} className={`theme-option ${prefs.theme === id ? 'selected' : ''}`} onClick={() => update('theme', id)}><div className={`theme-preview theme-${id}`}><span /><div><i /><i /><b /></div></div><span>{label}{prefs.theme === id ? <Check size={13} /> : null}</span></button>)}</div></SettingsGroup>
      <SettingsGroup title="字体">
        <SettingRow title="界面字体"><select aria-label="界面字体" value={prefs.uiFont} onChange={e => update('uiFont', e.target.value)}><option value="system">系统默认</option><option>Microsoft YaHei</option><option>Segoe UI</option></select></SettingRow>
        <SettingRow title="代码字体"><select aria-label="代码字体" value={prefs.codeFont} onChange={e => update('codeFont', e.target.value)}><option>Consolas</option><option>Cascadia Code</option><option>Courier New</option></select></SettingRow>
        <SettingRow title="界面字号"><select aria-label="界面字号" value={prefs.uiSize} onChange={e => update('uiSize', +e.target.value)}>{[12, 13, 14, 15, 16].map(n => <option key={n}>{n}</option>)}</select></SettingRow>
        <SettingRow title="对话字号"><select aria-label="对话字号" value={prefs.chatSize} onChange={e => update('chatSize', +e.target.value)}>{[13, 14, 15, 16, 18, 20].map(n => <option key={n}>{n}</option>)}</select></SettingRow>
        <div className="font-preview"><p>对话字体预览 · SuperCode</p><code>const supercode = 'ready';</code></div>
      </SettingsGroup>
      <SettingsGroup title="动画"><SettingRow title="界面动画" description="文字浮现与界面过渡。"><SettingsSwitch label="界面动画" checked={prefs.animations} change={v => update('animations', v)} /></SettingRow></SettingsGroup>
    </> : null}
    {tab === 'personalization' ? <SettingsGroup title="自定义指令"><div className="settings-card-editor"><p className="muted">为新聊天补充回复语言、工作习惯等偏好。</p><textarea aria-label="自定义指令" className="instructions-editor" value={instructions} onChange={e => setInstructions(e.target.value)} maxLength={16000} placeholder="例如：使用中文回复；优先使用项目已有依赖。" /><div className="settings-save-row"><span className="muted">新会话生效</span><button className="primary-button" disabled={!desktop || working} onClick={() => void run(async () => { await call('save_client_preferences', { instructions }); setMessage('已保存'); })}>保存</button></div></div></SettingsGroup> : null}
    {tab === 'skills' ? creating ? <form className="skill-editor" onSubmit={e => { e.preventDefault(); void run(async () => { await call('create_local_skill', { name, description, instructions: skillText }); setCreating(false); setName(''); setDescription(''); await loadSkills(); setMessage('技能已添加'); }); }}><div className="settings-section-heading"><h3>新建技能</h3><button type="button" className="icon-button" aria-label="取消新建技能" onClick={() => setCreating(false)}><X size={14} /></button></div><div className="preference-grid"><label>名称<input value={name} onChange={e => setName(e.target.value)} placeholder="my-skill" required /></label><label>用途<input value={description} onChange={e => setDescription(e.target.value)} required /></label></div><label htmlFor="skill-instructions">指令</label><textarea id="skill-instructions" value={skillText} onChange={e => setSkillText(e.target.value)} required /><button className="primary-button" disabled={working}>创建</button></form> : selected ? <><div className="settings-section-heading"><strong>{selected.name}</strong><button className="quiet-button" onClick={() => { setSelected(undefined); setSkillText(''); }}>返回列表</button></div><p className="skill-location">{skillSource(selected)}<br/>{selected.path}</p><pre className="skill-source">{skillText}</pre><button className="primary-button" disabled={busy || working} onClick={() => addSkill(selected)}>添加到对话</button></> : <><div className="search-field"><Search size={14} /><input placeholder="搜索技能" aria-label="搜索技能" value={search} onChange={e => setSearch(e.target.value)} /></div><>{warnings.map(warning => <p className="skill-list-warning" role="alert" key={warning}>{warning}</p>)}</><div className="extension-list">{skills.filter(s => `${s.name} ${s.description ?? ""} ${skillSource(s)}`.toLowerCase().includes(search.toLowerCase())).map(s => <button key={s.path} disabled={!!s.error || working} className="extension-row" title={s.path} onClick={() => void run(async () => { const text = await call<string>('read_skill', { path: s.path, projectId: projectId || null }); setSkillText(text); setSelected(s); })}><FileText size={17} /><span><strong>{s.name}</strong><small>{s.error ?? s.description ?? s.path}</small><small className="skill-origin">{skillSource(s)}</small></span><ChevronRight size={14} /></button>)}{working && !skills.length ? <p className="muted" role="status">正在读取技能…</p> : !skills.length ? <p className="muted">暂无本机技能</p> : !skills.some(s => `${s.name} ${s.description ?? ""} ${skillSource(s)}`.toLowerCase().includes(search.toLowerCase())) ? <p className="empty-filter">没有匹配的技能</p> : null}</div></> : null}
  </div>;
}
