import { lazy, Suspense, useEffect, useRef, useState, type ReactNode } from 'react';
import { ArrowUp, ExternalLink, MessageSquare, Square, X } from 'lucide-react';
import { call, subscribe } from './api';
import { createChatSession } from './chatSession';
import { Conversation } from './Conversation';
import { mergeEvent } from './events';
import { FollowupQueue, useFollowups, type FollowupPayload } from './Followups';
import { isActive, type Bootstrap, type Message, type RuntimeInfo, type Session, type RpcEvent } from './types';
const RequestCard=lazy(()=>import('./RequestCard'));
export interface SideDraft {key:string;text:string;payload?:FollowupPayload;sourceId?:string;projectId?:string;agent?:string;connectionId?:string}
export default function SideChat({draft,projectId,agent,connectionId,defaults,close,opened,openFile,showDiff,resizeHandle}:{draft:SideDraft;projectId:string;agent:string;connectionId:string;defaults:FollowupPayload;close:()=>void;opened:(session:Session)=>void;openFile:(path:string,line?:number,workspaceSessionId?:string)=>void;resizeHandle?:ReactNode;showDiff:(name:string,text:string)=>void}){
  const [input,setInput]=useState(draft.text);const [session,setSession]=useState<Session>();const [messages,setMessages]=useState<Message[]>([]);const [requests,setRequests]=useState<RpcEvent[]>([]);const [error,setError]=useState('');const [sending,setSending]=useState(false);
  const current=useRef(session);current.current=session;const area=useRef<HTMLDivElement>(null);const timer=useRef<ReturnType<typeof setTimeout>|undefined>(undefined);
  const options=useRef(draft.payload??defaults);const source=useRef(draft.sourceId);
  const followups=useFollowups(session?.id??'',e=>setError(String(e)));
  async function refresh(){const s=current.current;if(!s)return;const [data,items,info]=await Promise.all([call<Bootstrap>('bootstrap'),call<Message[]>('list_messages',{sessionId:s.id,limit:120}),call<RuntimeInfo>('runtime_info')]);const saved=data.sessions.find(x=>x.id===s.id);if(saved){current.current=saved;setSession(saved);setRequests(info.requests.filter(r=>r.params?.threadId===saved.nativeId));}setMessages(items);}
  useEffect(()=>{let disposed=false;let off:(()=>void)|undefined;const schedule=()=>{if(!current.current||timer.current)return;timer.current=setTimeout(()=>{timer.current=undefined;void refresh().catch(e=>setError(String(e)));},150);};void subscribe(e=>{if(e.method==='turn/started'||e.method==='turn/completed'){schedule();return;}const s=current.current;if(s&&e.params?.threadId===s.nativeId){setMessages(old=>mergeEvent(old,e,s.id));if(e.id!=null)setRequests(old=>old.some(r=>r.id===e.id)?old:[...old,e]);if(e.method==='serverRequest/resolved')setRequests(old=>old.filter(r=>r.id!==e.params?.requestId));}},()=>{},schedule,schedule).then(fn=>{if(disposed)fn();else off=fn;});return()=>{disposed=true;off?.();if(timer.current)clearTimeout(timer.current);};},[]);
  useEffect(()=>{if(area.current)area.current.scrollTop=area.current.scrollHeight;},[messages]);
  async function change(id:string,action:string,text?:string){try{await call('change_followup',{id,action,text:text??null});await followups.reload();}catch(e){setError(String(e));throw e;}}
  async function send(){if(sending||!input.trim())return;setSending(true);setError('');try{let s=current.current;if(!s){s=await createChatSession({projectId,agent,connectionId,model:options.current.model??''});current.current=s;setSession(s);}await call('enqueue_followup',{sessionId:s.id,payload:{...options.current,text:input}});if(source.current){await call('change_followup',{id:source.current,action:'remove',text:null});source.current=undefined;}options.current={...options.current,attachments:[]};setInput('');await followups.reload();await refresh();}catch(e){setError(String(e));}finally{setSending(false);}}
  return <aside className="side-chat" aria-label="侧边聊天">{resizeHandle}<header><MessageSquare size={16}/><strong>侧边聊天</strong>{session?<button className="icon-button" aria-label="打开侧边聊天的独立窗口" onClick={()=>void call('open_chat_window',{sessionId:session.id}).catch(e=>setError(String(e)))}><ExternalLink size={15}/></button>:null}<button className="icon-button" aria-label="收起侧边聊天" onClick={()=>{if(session)opened(session);close();}}><X size={16}/></button></header>
    <div className="side-chat-scroll" ref={area}>{messages.length?<Conversation messages={messages} agentName={agent} autoExpand={false} projectId={projectId} sessionId={session?.id} openFile={(path,line)=>openFile(path,line,session?.id)} showDiff={showDiff}/>:<p className="muted">围绕选中内容开启一个独立对话</p>}{requests.map(r=><Suspense key={String(r.id)} fallback={<p>正在加载确认请求…</p>}><RequestCard request={r} respond={async result=>{await call('respond_request',{id:r.id,result});await refresh();}}/></Suspense>)}</div>
    <footer>{error?<p className="side-chat-error" role="alert">{error}</p>:null}{followups.rows.length&&!session?.turnId?<p className="muted">已排队，将在当前任务完成后发送</p>:null}<FollowupQueue rows={followups.rows} agent={agent} turnId={session?.turnId} steeringMode={followups.steeringMode} change={change} steer={async id=>{try{await call('steer_followup',{id,expectedTurnId:session?.turnId});await followups.reload();}catch(e){setError(String(e));}}} openSide={row=>{void change(row.id,'pause').then(()=>{options.current=row.payload;source.current=row.id;setInput(row.payload.text);});}}/><form onSubmit={e=>{e.preventDefault();void send();}}><textarea autoFocus aria-label="侧边聊天消息" value={input} rows={3} placeholder="继续提问…" onChange={e=>setInput(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.nativeEvent.isComposing){e.preventDefault();void send();}}}/><div><span>{options.current.model||agent}</span>{session&&isActive(session.status)?<button type="button" className="icon-button" aria-label="停止侧边聊天任务" onClick={()=>void call('interrupt_turn',{sessionId:session.id}).catch(e=>setError(String(e)))}><Square size={13}/></button>:null}<button className="send-button" type="submit" disabled={sending||!input.trim()} aria-label="发送侧边聊天消息"><ArrowUp size={16}/></button></div></form></footer>
  </aside>;
}
